command_socket: /run/toponavi/executor/command.ipc

pins:
  motor:
    left:
      forward: 1
      backward: 4
    right:
      forward: 5
      backward: 6
  ultrasonic:
    trigger: 28
    echo: 29

speed_command: 0.7
control_interval: 0.1
distance_setpoint: 0.5

distance_statisics:
  window_size: 7
  median_filter:
    window_size: 5

normal_state:
  pid:
    kp: -1.7
    ti: 20
    td: 1
    max_abs_i: 4
  disturb_squared_error_thre: 0.001
  disturb_max_raw_thre: 5
  bias_timeout: 2
  speed: 0.53
  approaching_angle: 0.15

chaos_state:
  pid:
    max_abs_command: 0.2
    kp: -1
    ti: 10
    td: 0
    max_abs_i: 2
  disturb_squared_error_thre: 0.001
  blind_thre: 5
  to_normal_time: 0.5

turn_state:
  omega: 2.6 # 角速度
  alpha: 20 # 角加速度
  turn_command: 0.5

disturbed_state:
  initial_silent: 0.5
  to_normal_time: 0.7
  disturb_squared_error_thre: 0.001
  blind_thre: 5

stablized_state:
  max_no_bias: 0.05
  min_no_bias: -0.1

blind_state:
  restore_thre: 2

scan_state:
  turn_command: 0.5
